const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../preview');
for (const file of ['workspace.js','auth.js','account.css','config.js','vendor/supabase.js']) {
  if (!fs.existsSync(path.join(root,file))) throw new Error(`Missing dependency: ${file}`);
}
const scriptTags = '<script src="vendor/supabase.js" defer></script><script src="config.js" defer></script><script src="preview.js" defer></script><script src="auth.js" defer></script>';
const head = title => `<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="HomaCare — kết nối chăm sóc tại nhà, đồng hành từ xa."><title>${title} · HomaCare</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="account.css">${scriptTags}<link rel="apple-touch-icon" href="assets/app-icon-h.png?v=2"><link rel="icon" type="image/png" href="assets/app-icon-h.png?v=2"><link rel="manifest" href="manifest.webmanifest?v=2"><meta name="apple-mobile-web-app-title" content="HomaCare"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="theme-color" content="#0F4C46"></head>`;
const brand = '<a class="brand" href="index.html" aria-label="HomaCare — Trang chủ"><span class="brand-icon"><img src="assets/logo.png" alt=""></span><span class="brand-text">Homa<span>Care</span></span></a>';
const roleDialog = `<div class="modal-overlay" id="role-modal"><div class="modal role-modal" role="dialog" aria-modal="true" aria-labelledby="role-title"><button class="close-modal" aria-label="Đóng">×</button><div class="eyebrow">Cùng HomaCare đồng hành</div><h2 id="role-title">Bạn đến với vai trò nào?</h2><p>Chọn không gian phù hợp với bạn.</p><div class="role-options"><a class="role-option" data-role-link="family" href="auth.html?role=family"><span class="icon-box" data-icon="heart"></span><span><strong>Gia đình</strong><small>Sắp xếp chăm sóc và dõi theo người thân.</small></span><span data-icon="arrow"></span></a><a class="role-option" data-role-link="caregiver" href="auth.html?role=caregiver"><span class="icon-box peach" data-icon="users"></span><span><strong>Chuyên viên chăm sóc</strong><small>Nhận lịch và ghi lại từng buổi đồng hành.</small></span><span data-icon="arrow"></span></a><a class="role-option" data-role-link="coordinator" href="auth.html?role=coordinator"><span class="icon-box" data-icon="shield"></span><span><strong>Điều phối viên</strong><small>Không gian quản lý dành cho đội ngũ HomaCare.</small></span><span data-icon="arrow"></span></a></div></div></div>`;
const auth = `${head('Tài khoản')}<body class="account-page"><header class="site-header"><nav class="container nav">${brand}<a class="text-link" style="margin:0" href="index.html">Về trang chủ <span data-icon="arrow"></span></a></nav></header><main class="account-layout container"><section class="account-story"><div class="eyebrow">Chăm sóc tại nhà · Đồng hành từ xa</div><h1>Thêm kết nối.<br><em>Trọn quan tâm.</em></h1><p>Một nơi để gia đình, chuyên viên và người điều phối cùng chăm lo cho những người thân yêu.</p><div class="account-symbol"><img src="assets/app-icon-h.png" alt="Biểu tượng HomaCare"></div><div class="account-trust"><span data-icon="shield"></span><span>Lịch chăm sóc rõ ràng.<br>Nhật ký luôn bên bạn.</span></div></section><section class="account-card"><div class="account-role-row"><span class="pill" id="auth-role-label">Gia đình</span><button class="plain-link" data-modal="role-modal">Đổi vai trò</button></div><h2 id="auth-title">Chào mừng bạn trở lại.</h2><p id="auth-description">Đăng nhập để tiếp tục hành trình chăm sóc của bạn.</p><div class="auth-tabs" id="auth-tabs" role="tablist" aria-label="Tài khoản"><button class="active" role="tab" aria-selected="true" data-auth-mode="login">Đăng nhập</button><button role="tab" aria-selected="false" data-auth-mode="signup">Đăng ký</button></div><form id="account-form"><div class="field" data-auth-field="name" hidden><label for="account-name">Họ và tên</label><input id="account-name" name="name" autocomplete="name" maxlength="100" placeholder="Tên để HomaCare xưng hô với bạn"></div><div class="field" data-auth-field="email"><label for="account-email">Email</label><input id="account-email" name="email" type="email" autocomplete="email" maxlength="254" placeholder="ban@example.com" required></div><div class="field" data-auth-field="password"><label for="account-password">Mật khẩu</label><div class="password-field"><input id="account-password" name="password" type="password" autocomplete="current-password" required><button type="button" id="toggle-password" aria-label="Hiện mật khẩu">Hiện</button></div></div><div class="field" data-auth-field="confirmation" hidden><label for="account-confirmation">Nhập lại mật khẩu</label><input id="account-confirmation" type="password" autocomplete="new-password"></div><div class="auth-help"><button class="plain-link" id="forgot-password" type="button">Quên mật khẩu?</button><button class="plain-link" id="auth-back-login" type="button" hidden>Quay lại đăng nhập</button></div><div id="auth-message" class="form-message" role="status" aria-live="polite"></div><button class="btn" type="submit" id="auth-submit">Đăng nhập</button></form><div class="account-footer"><span data-icon="heart"></span>Gửi trọn quan tâm, vẹn tròn đạo hiếu.</div></section></main>${roleDialog}</body></html>`;
fs.writeFileSync(path.join(root,'auth.html'), auth);
const navItems = {
  family: [['home','family.html','Tổng quan'],['calendar','#schedule','Lịch chăm sóc'],['report','#latest-report','Nhật ký chăm sóc'],['heart','index.html#services','Dịch vụ']],
  caregiver: [['calendar','caregiver.html','Ca chăm sóc'],['report','#care-work','Ghi nhận hoạt động'],['book','index.html#staff','Quy trình chăm sóc']],
  coordinator: [['home','coordinator.html','Tổng quan'],['calendar','#requests','Điều phối ca'],['users','#staff-list','Chuyên viên']]
};
const labels = { family:'Gia đình', caregiver:'Chuyên viên chăm sóc', coordinator:'Điều phối viên' };
for (const role of Object.keys(labels)) {
  const sidebar = navItems[role].map(([icon,href,label],i)=>`<a ${i===0?'class="active"':''} href="${href}"><span data-icon="${icon}"></span>${label}</a>`).join('');
  const page = `${head(labels[role]).replace('</head>','<script src="workspace.js" defer></script></head>')}<body class="workspace" data-auth-required="${role}"><header class="site-header"><nav class="container nav workspace-nav">${brand}<a class="text-link workspace-home" href="index.html" style="margin:0">Trang chủ</a><div class="account-nav"><span class="pill">${labels[role]}</span><button class="plain-link" id="sign-out">Đăng xuất</button></div></nav></header><div class="access-state container" id="access-state" role="status"><span class="loading-dot"></span><h1>Đang kết nối tài khoản…</h1><p>Không gian chăm sóc của bạn đang được chuẩn bị.</p></div><main class="container workspace-content" hidden id="workspace-main"><div class="dashboard-layout"><aside class="sidebar">${sidebar}<div class="sidebar-note">Gửi trọn quan tâm,<br>vẹn tròn đạo hiếu.</div></aside><div id="workspace-view"></div></div></main><div id="workspace-modals"></div></body></html>`;
  fs.writeFileSync(path.join(root,`${role}.html`), page);
}
let home = fs.readFileSync(path.join(root,'index.html'),'utf8');
if (!home.includes('src="config.js"')) {
home = home.replace('<script src="preview.js" defer></script>', scriptTags).replace('</head>','<link rel="stylesheet" href="account.css"></head>');
home = home.replace(/<div class="demo-ribbon">.*?<\/div><\/div>\s*/,'');
home = home.replaceAll('Trải nghiệm nền tảng','Đăng nhập / Đăng ký').replaceAll('Trải nghiệm bản mẫu','Bắt đầu đồng hành').replaceAll('GÓI TRẢI NGHIỆM TRONG BẢN XEM TRƯỚC','CHĂM SÓC THEO BUỔI');
home = home.replaceAll('Hồ sơ mẫu','Chuyên viên HomaCare');
home = home.replaceAll('Các bài đọc mẫu về người cao tuổi ở Việt Nam và trên thế giới, dẫn đến nguồn gốc để bạn tìm hiểu thêm.','Các bài đọc về người cao tuổi ở Việt Nam và trên thế giới, cùng nguồn tham khảo để bạn tìm hiểu thêm.');
home = home.replaceAll('Mai Anh đang đồng hành','Chuyên viên đang đồng hành').replaceAll('Nguyễn Mai Anh','Người đồng hành HomaCare');
home = home.replaceAll('Chuyên viên chăm sóc tại gia · Hà Nội','Lắng nghe · Chăm sóc · Kết nối');
home = home.replace(/<p class="tiny-note">Hồ sơ minh họa.*?<\/p>/,'');
home = home.replace(/<p class="tiny-note">Bài đọc minh họa.*?<\/p>/,'');
home = home.replace(/<p>Khám phá cách một ca chăm sóc được kết nối, điều phối và cập nhật cho gia đình\.<\/p>/,'<p>Bắt đầu lộ trình chăm sóc và nhận nhật ký sau mỗi buổi đồng hành.</p>');
home = home.replaceAll('Bản xem trước giao diện · 2026','© 2026 HomaCare');
home = home.replaceAll('Bản xem trước tập trung vào ca chăm sóc Ân cần.','HomaCare hiện tập trung vào ca chăm sóc Ân cần.');
home = home.replaceAll('Xem ca Ân cần mẫu','Đặt ca Ân cần').replaceAll('Xem nhật ký mẫu','Xem nhật ký chăm sóc').replaceAll('Khám phá ca Ân cần','Đặt ca Ân cần');
home = home.replaceAll('Xem giao diện điều phối','Kết nối với HomaCare');
home = home.replaceAll('href="coordinator.html"','href="auth.html?role=family"');
home = home.replaceAll('href="family.html?booking=1"','href="auth.html?role=family&amp;booking=1"');
home = home.replaceAll('href="family.html"','href="auth.html?role=family" data-modal="role-modal"');
home = home.replace('<a href="#staff">Chuyên viên</a></div><a class="btn small"', '<a href="#staff">Chuyên viên</a><a class="mobile-account-entry" href="auth.html?role=family" data-modal="role-modal">Đăng nhập / Đăng ký</a></div><a class="btn small"');
home = home.replace('</body>',roleDialog+'</body>');
}
home = home.replace('<a class="mobile-account-entry" href="auth.html?role=family" data-modal="role-modal">Đăng nhập / Đăng ký</a>', '<div class="mobile-account-entry" data-home-account="mobile"><a href="auth.html?role=family" data-modal="role-modal">Đăng nhập / Đăng ký</a></div>');
const homeAccountEntry = '<div class="home-account-actions" data-home-account="desktop"><a class="btn small" href="auth.html?role=family" data-modal="role-modal"><span class="home-account-label">Đăng nhập / Đăng ký</span><span data-icon="arrow"></span></a></div>';
if (!home.includes('data-home-account="desktop"')) home = home.replace('<a class="btn small" href="auth.html?role=family" data-modal="role-modal">Đăng nhập / Đăng ký <span data-icon="arrow"></span></a>', homeAccountEntry);
// The account entry stays visible in the mobile header; no hamburger is needed.
home = home.replace(/<div class="mobile-account-entry" data-home-account="mobile">[\s\S]*?<\/div>/, '');
home = home.replace(/<button class="mobile-menu-button"[^>]*><\/button>/, '');
// Normalize the end of the header so rebuilding cannot nest account wrappers.
home = home.replace(/<div class="home-account-actions" data-home-account="desktop">[\s\S]*?<\/nav>/, homeAccountEntry + '</nav>');
fs.writeFileSync(path.join(root,'index.html'), home);
const previous = fs.readFileSync(path.join(root,'preview.js'),'utf8');
fs.writeFileSync(path.join(root,'preview.js'), previous.split(/\r?\n/).slice(0,2).join('\n') + '\n' + fs.readFileSync(path.join(__dirname,'ui-handlers.txt'),'utf8'));
