(() => {
  const role = document.body.dataset.authRequired;
  if (!role) return;
  const auth = window.HomaAuth, ui = window.HomaUI;
  const main = document.getElementById('workspace-main'), access = document.getElementById('access-state'), view = document.getElementById('workspace-view'), modals = document.getElementById('workspace-modals');
  const state = { profile: null, relatives: [], visits: [], staff: [], selected: null, filter: 'all', busy: false };
  const statuses = { pending: 'Chờ phân công', assigned: 'Đã phân công', in_progress: 'Đang chăm sóc', completed: 'Hoàn thành' };
  const taskLabels = ['Hỗ trợ bữa tối', 'Đồng hành vận động nhẹ', 'Trò chuyện & nhắc lịch sinh hoạt', 'Kiểm tra an toàn trước khi kết thúc'];
  const esc = text => String(text ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const initials = name => esc(String(name || 'HC').trim().split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase());
  const relation = v => Array.isArray(v.relative) ? v.relative[0] : v.relative;
  const caregiver = v => Array.isArray(v.caregiver) ? v.caregiver[0] : v.caregiver;
  const family = v => Array.isArray(v.family) ? v.family[0] : v.family;
  const calendar = date => `<div class="calendar-tile"><span>THÁNG ${Number(date.slice(5,7))}</span><strong>${date.slice(8,10)}</strong></div>`;
  const dateText = date => date ? new Intl.DateTimeFormat('vi-VN', { dateStyle: 'medium', timeZone:'Asia/Ho_Chi_Minh' }).format(new Date(date + 'T12:00:00+07:00')) : '';
  const timeText = date => date ? new Intl.DateTimeFormat('vi-VN', {dateStyle:'short',timeStyle:'short', timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(date)) : '';
  const today = () => { const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Asia/Ho_Chi_Minh'}).formatToParts(new Date()); return ['year','month','day'].map(t=>parts.find(p=>p.type===t).value).join('-'); };
  const pill = status => `<span class="pill ${status==='pending'?'orange':status==='completed'?'blue':''}">${statuses[status] || ''}</span>`;
  const empty = (title,copy,action='') => `<div class="empty-state"><span class="icon-box" data-icon="heart"></span><h3>${esc(title)}</h3><p>${esc(copy)}</p>${action}</div>`;
  const heading = (copy) => `<div class="dashboard-heading"><div><h1>Chào ${esc(state.profile.full_name)},</h1><p>${esc(copy)}</p></div><div class="workspace-actions"><button class="plain-link" data-action="refresh">Cập nhật</button>${role==='family'?'<button class="btn small" data-action="book">Đặt ca chăm sóc <span data-icon="arrow"></span></button>':''}</div></div>`;
  const modal = (id,title,body,eyebrow='Cùng HomaCare đồng hành') => `<div class="modal-overlay" id="${id}"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="${id}-title"><button class="close-modal" aria-label="Đóng">×</button><div class="eyebrow">${eyebrow}</div><h2 id="${id}-title">${title}</h2>${body}<div class="form-message" data-form-message role="status" aria-live="polite"></div></div></div>`;
  function issue(error) {
    const text=String(error?.message || '');
    if(error?.code==='23505') return 'Lịch này đã được sắp xếp. Hãy chọn ngày hoặc chuyên viên khác.';
    if(/invalid_state/.test(text)) return 'Ca này vừa được cập nhật. Hãy tải lại danh sách trước khi thao tác.';
    if(/not_allowed|42501/.test(text)) return 'Bạn không có quyền thực hiện thao tác này.';
    if(/invalid_date/.test(text)) return 'Hãy chọn ngày từ hôm nay trở đi.';
    if(/incomplete_tasks/.test(text)) return 'Bạn cần ghi nhận đủ các hoạt động trước khi hoàn thành ca.';
    if(/invalid_report/.test(text)) return 'Nhật ký cần ít nhất 10 ký tự.';
    if(/fetch|network/i.test(text)) return 'Chưa kết nối được. Hãy kiểm tra mạng rồi thử lại.';
    return 'Chưa lưu được thông tin. Vui lòng thử lại.';
  }
  function blocked(title,copy,link='auth.html?role='+role) { main.hidden=true; access.hidden=false; access.innerHTML=`<span class="icon-box" data-icon="shield"></span><h1>${esc(title)}</h1><p>${esc(copy)}</p><a class="btn" href="${link}">Đến trang đăng nhập</a>`; ui.icons(access); }
  async function query(request) { const result=await request; if(result.error) throw result.error; return result.data; }
  async function load() {
    const client=auth.client;
    const data=await query(client.from('visits').select('*,relative:relatives(*),caregiver:profiles!visits_caregiver_id_fkey(id,full_name),family:profiles!visits_family_id_fkey(id,full_name)').order('care_date',{ascending:true}).order('created_at',{ascending:true}));
    state.visits=data || [];
    if(role==='family') state.relatives=await query(client.from('relatives').select('*').order('created_at',{ascending:true}));
    if(role==='coordinator') state.staff=await query(client.from('profiles').select('id,full_name').eq('role','caregiver').order('full_name'));
    render();
  }
  function renderFamily() {
    const person=state.relatives[0], next=state.visits.find(v=>v.status!=='completed'), reports=state.visits.filter(v=>v.status==='completed').sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at));
    const latest=reports[0];
    const personCard=person?`<section class="panel senior-panel"><div class="senior-info"><div><div class="eyebrow">NGƯỜI THÂN CỦA BẠN</div><h2>${esc(person.relationship)} · ${esc(person.full_name)}</h2><p>${person.age} tuổi · ${esc(person.area)}</p></div><span class="avatar">${initials(person.full_name)}</span></div><div class="senior-details"><div><span>Thói quen & mong muốn</span><strong>${esc(person.preferences || 'Chưa ghi nhận thêm')}</strong></div></div><div class="relative-actions"><button class="btn secondary small" data-modal="relative-modal">Thêm người thân</button></div>${state.relatives.length>1?`<p class="tiny-note">Bạn đang chăm lo cho ${state.relatives.length} người thân. Chọn hồ sơ khi đặt ca.</p>`:''}</section>`:`<section class="panel">${empty('Bắt đầu từ người thân của bạn.','Thêm một vài thông tin để chúng tôi sắp xếp sự đồng hành phù hợp.','<button class="btn" data-modal="relative-modal">Thêm người thân</button>')}</section>`;
    const schedule=`<section class="panel" id="schedule"><div class="panel-title"><h2>Lịch chăm sóc</h2>${next?pill(next.status):''}</div>${state.visits.length?`<div class="booking-list">${state.visits.map(v=>`<div class="visit-row">${calendar(v.care_date)}<div style="flex:1"><strong>Ân cần · ${esc(relation(v)?.full_name)}</strong><p>${dateText(v.care_date)} · 18:00–22:00</p><p>${esc(caregiver(v)?.full_name || 'Đang chờ sắp xếp chuyên viên')}</p></div>${pill(v.status)}</div>`).join('')}</div>`:empty('Chưa có lịch chăm sóc.','Sau khi thêm người thân, bạn có thể lựa chọn buổi đồng hành đầu tiên.')}</section>`;
    const report=`<section class="panel" id="latest-report"><div class="panel-title"><h2>Nhật ký chăm sóc gần nhất</h2>${latest?pill(latest.status):''}</div>${latest?`<div class="visit-row">${calendar(latest.care_date)}<div><strong>${esc(relation(latest)?.full_name)}</strong><p>${esc(caregiver(latest)?.full_name)} · 18:00–22:00</p></div></div><div class="report-checks">${taskLabels.map(t=>`<div><span data-icon="check"></span>${t}</div>`).join('')}</div><div class="report-note">${esc(latest.report_text)}</div><p style="font-size:12px">${esc(latest.mood)}</p>${latest.next_note?`<p class="report-hint">Lần tới: ${esc(latest.next_note)}</p>`:''}<div style="margin-top:20px"><p style="font-size:12px">Bạn thấy ca chăm sóc thế nào?</p><div class="rating" aria-label="Đánh giá ca chăm sóc">${[1,2,3,4,5].map(n=>`<button class="${n<=(latest.rating||0)?'selected':''}" aria-label="${n} sao" data-action="rate" data-id="${latest.id}" data-rating="${n}">★</button>`).join('')}</div></div>`:empty('Nhật ký sẽ xuất hiện tại đây.','Sau mỗi ca, chuyên viên ghi lại các hoạt động và những điều gia đình cần lưu ý.')}</section>`;
    const timeline=next || latest;
    const moments=timeline?[[timeline.created_at,'Gia đình gửi yêu cầu'],[timeline.assigned_at,'Điều phối viên phân công'],[timeline.started_at,'Chuyên viên bắt đầu ca'],[timeline.completed_at,'Nhật ký gửi đến gia đình']].filter(x=>x[0]):[];
    view.innerHTML=heading('Cùng chăm lo cho những người thân yêu.')+`<div class="dashboard-grid">${personCard}${schedule}${report}<section class="panel subtle"><div class="panel-title"><h2>Mọi bước đều rõ ràng</h2><span data-icon="shield"></span></div>${moments.length?`<div class="timeline">${moments.map(([date,title])=>`<div class="timeline-item"><strong>${title}</strong><small>${timeText(date)}</small></div>`).join('')}</div>`:empty('Một hành trình có người đồng hành.','Yêu cầu → Phân công → Chăm sóc → Nhật ký. Bạn theo dõi từng bước ngay tại đây.')}<div class="warning-note">Nhật ký ghi nhận sinh hoạt. HomaCare không đưa ra chẩn đoán hoặc quyết định điều trị.</div></section></div><section class="booking-banner"><div><h3>Thêm một buổi đồng hành bên người thân.</h3><p>Lựa chọn lịch phù hợp, HomaCare giúp bạn sắp xếp.</p></div><button class="btn small" data-action="book">Đặt ca Ân cần <span data-icon="arrow"></span></button></section>`;
    modals.innerHTML=modal('relative-modal','Thấu hiểu người thân của bạn.',`<p>Những thông tin cơ bản giúp chuyên viên đồng hành phù hợp hơn.</p><form id="relative-form"><div class="field"><label for="relative-name">Họ và tên người thân</label><input id="relative-name" name="full_name" required minlength="2" maxlength="100" autocomplete="off"></div><div class="field-row"><div class="field"><label for="relative-relationship">Mối quan hệ với bạn</label><select id="relative-relationship" name="relationship"><option>Mẹ</option><option>Bố</option><option>Ông</option><option>Bà</option><option>Người thân</option></select></div><div class="field"><label for="relative-age">Tuổi</label><input id="relative-age" name="age" type="number" required min="18" max="120" inputmode="numeric"></div></div><div class="field"><label for="relative-area">Khu vực chăm sóc</label><input id="relative-area" name="area" required minlength="2" maxlength="200" placeholder="Quận/huyện, tỉnh/thành phố"></div><div class="field"><label for="relative-preferences">Thói quen & mong muốn</label><textarea id="relative-preferences" name="preferences" maxlength="2000" placeholder="Người thân thích làm gì? Có điều gì cần lưu ý?"></textarea></div><button class="btn" type="submit">Lưu người thân</button></form>`)+modal('booking-modal','Đặt một ca Ân cần.',`<p>4 giờ đồng hành tại nhà · 18:00–22:00<br>Giá dịch vụ: 320.000đ/buổi</p><form id="booking-form"><div class="field"><label for="booking-relative">Người thân</label><select id="booking-relative" name="relative_id" required>${state.relatives.map(r=>`<option value="${r.id}">${esc(r.relationship)} · ${esc(r.full_name)}</option>`).join('')}</select></div><div class="field"><label for="booking-date">Ngày chăm sóc</label><input id="booking-date" name="care_date" type="date" min="${today()}" value="${today()}" required></div><div class="field"><label for="booking-note">Điều bạn muốn chuyên viên lưu ý</label><textarea id="booking-note" name="care_note" maxlength="2000"></textarea></div><button class="btn" type="submit">Gửi yêu cầu chăm sóc</button><p class="tiny-note">Điều phối viên sẽ tiếp nhận và phân công chuyên viên. Bạn chưa cần thanh toán tại bước này.</p></form>`,'Bắt đầu lộ trình');
  }
  function renderCaregiver() {
    const openVisits=state.visits.filter(v=>v.status!=='completed');
    const selected=openVisits.find(v=>v.id===state.selected) || openVisits[0]; state.selected=selected?.id || null;
    const cards=`<section class="panel"><div class="panel-title"><h2>Ca được phân công</h2><span class="pill">${openVisits.length} ca</span></div>${openVisits.length?`<div class="visit-list">${openVisits.map(v=>`<button class="visit-choice ${v.id===state.selected?'selected':''}" data-action="choose-visit" data-id="${v.id}"><strong>${esc(relation(v)?.full_name)}</strong><span>${dateText(v.care_date)} · 18:00–22:00</span><div style="margin-top:8px">${pill(v.status)}</div></button>`).join('')}</div>`:empty('Chưa có ca được phân công.','Lịch chăm sóc sẽ xuất hiện khi điều phối viên sắp xếp ca cho bạn.')}</section>`;
    const detail=selected?`<section class="panel visit-hero"><div class="eyebrow">CA ÂN CẦN · ${dateText(selected.care_date)}</div><h2>Đồng hành cùng ${esc(relation(selected)?.full_name)}</h2><p>${relation(selected)?.age || ''} tuổi · ${esc(relation(selected)?.area)}</p><div class="visit-meta"><span>18:00–22:00</span><span>4 giờ</span></div><div class="report-note">${esc(relation(selected)?.preferences || 'Hãy lắng nghe mong muốn của người thân trong buổi đồng hành.')}</div>${selected.care_note?`<p>Gia đình lưu ý: ${esc(selected.care_note)}</p>`:''}<button class="btn" data-action="start" data-id="${selected.id}" ${selected.status==='in_progress'?'disabled':''}>${selected.status==='in_progress'?'Đã bắt đầu lúc '+timeText(selected.started_at):'Bắt đầu ca chăm sóc'}</button></section><section class="panel" id="care-work"><div class="panel-title"><h2>Hoạt động trong ca</h2><span class="mini-label" id="task-count">0/4 hoạt động</span></div><div class="progress-bar"><span></span></div><div class="task-list">${taskLabels.map((t,n)=>`<label class="task"><input type="checkbox" name="task-${n}" ${selected.status!=='in_progress'?'disabled':''}><span>${t}</span></label>`).join('')}</div></section>`:'';
    const report=selected?`<section class="panel"><div class="caregiver-summary"><span class="avatar">${initials(state.profile.full_name)}</span><div><h3>${esc(state.profile.full_name)}</h3><p>Chuyên viên chăm sóc</p></div></div><div class="panel-title"><h2>Nhật ký sau ca</h2></div><form id="report-form" data-visit="${selected.id}"><div class="field"><label for="mood">Ghi nhận chung</label><select id="mood" name="mood"><option>Sinh hoạt như thường ngày</option><option>Có điều gia đình cần lưu ý</option><option>Cần điều phối viên liên hệ</option></select></div><div class="field"><label for="report-note">Nội dung gửi cho gia đình</label><textarea id="report-note" name="report_text" required minlength="10" maxlength="4000" placeholder="Các hoạt động đã thực hiện và những điều cần lưu ý"></textarea></div><div class="field"><label for="next-note">Mong muốn cho lần tới</label><input id="next-note" name="next_note" maxlength="2000"></div><div class="form-message" data-form-message role="status"></div><button class="btn" type="submit" style="width:100%" ${selected.status!=='in_progress'?'disabled':''}>Hoàn thành & gửi báo cáo</button></form><p class="report-hint">Nhật ký được gửi đến gia đình khi bạn hoàn thành ca.</p></section>`:'';
    const completed=state.visits.filter(v=>v.status==='completed');
    view.innerHTML=heading('Một buổi đồng hành, nhiều điều ý nghĩa.')+`<div class="care-layout"><div>${cards}${detail}</div><div>${report}<section class="panel subtle"><div class="panel-title"><h2>Những buổi đã đồng hành</h2><span class="pill blue">${completed.length} ca</span></div>${completed.length?completed.map(v=>`<div class="staff-item"><span class="avatar teal">${initials(relation(v)?.full_name)}</span><div><strong>${esc(relation(v)?.full_name)}</strong><p>${dateText(v.care_date)}</p></div>${pill(v.status)}</div>`).join(''):empty('Từng buổi đồng hành đều ý nghĩa.','Các ca đã hoàn thành được ghi lại ở đây.')}<div class="warning-note">Ghi nhận hoạt động sinh hoạt, không chẩn đoán tình trạng y tế.</div></section></div></div>`;
    modals.innerHTML='';
  }
  function filteredVisits() { return state.visits.filter(v=>state.filter==='all'||state.filter===v.status); }
  function renderCoordinator() {
    const counts={pending:0,assigned:0,in_progress:0,completed:0}; state.visits.forEach(v=>counts[v.status]++);
    const rows=filteredVisits();
    view.innerHTML=heading('Kết nối gia đình và chuyên viên, theo dõi từng bước chăm sóc.')+`<div class="mini-grid"><div class="metric"><span>CHỜ PHÂN CÔNG</span><strong>${counts.pending}</strong><small>Yêu cầu cần tiếp nhận</small></div><div class="metric"><span>ĐANG ĐỒNG HÀNH</span><strong>${counts.assigned+counts.in_progress}</strong><small>Chuyên viên đã được sắp xếp</small></div><div class="metric"><span>HOÀN THÀNH</span><strong>${counts.completed}</strong><small>Đã có nhật ký chăm sóc</small></div></div><section class="panel" id="requests"><div class="panel-title"><h2>Danh sách ca chăm sóc</h2><span class="mini-label">${state.visits.length} ca</span></div><div class="tabs">${[['all','Tất cả'],['pending','Chờ phân công'],['assigned','Đã phân công'],['in_progress','Đang chăm sóc'],['completed','Hoàn thành']].map(([value,label])=>`<button data-action="filter" data-filter="${value}" class="${value===state.filter?'active':''}">${label}</button>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>Người thân</th><th>Lịch chăm sóc</th><th>Chuyên viên</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${rows.map(v=>`<tr><td><strong>${esc(relation(v)?.full_name)}</strong><span>Gia đình: ${esc(family(v)?.full_name)}</span></td><td><strong>${dateText(v.care_date)}</strong><span>Ân cần · 18:00–22:00</span></td><td>${esc(caregiver(v)?.full_name || 'Chưa phân công')}</td><td>${pill(v.status)}</td><td><button class="${v.status==='pending'?'btn small':'plain-link'}" data-action="${v.status==='pending'?'assign':'detail'}" data-id="${v.id}">${v.status==='pending'?'Phân công':'Xem ca'}</button></td></tr>`).join('')}</tbody></table>${!rows.length?'<div class="table-empty">Chưa có ca chăm sóc trong danh sách này.</div>':''}</div></section><div class="dashboard-grid dashboard-top-gap"><section class="panel" id="staff-list"><div class="panel-title"><h2>Chuyên viên chăm sóc</h2><span class="mini-label">${state.staff.length} chuyên viên</span></div>${state.staff.length?state.staff.map(p=>`<div class="staff-item"><span class="avatar">${initials(p.full_name)}</span><div><strong>${esc(p.full_name)}</strong><p>Tài khoản chuyên viên chăm sóc</p></div></div>`).join(''):empty('Đội ngũ sẽ xuất hiện tại đây.','Chuyên viên tạo tài khoản và xác nhận email trước khi được phân công.')}</section><section class="panel subtle"><div class="panel-title"><h2>Điều cần theo dõi</h2><span data-icon="bell"></span></div><p>Xác nhận nhu cầu với gia đình, kiểm tra lịch chuyên viên và theo dõi nhật ký sau mỗi ca.</p><div class="warning-note">Với nhu cầu vượt phạm vi hỗ trợ sinh hoạt, trao đổi cùng gia đình để kết nối đơn vị chuyên môn phù hợp.</div></section></div>`;
    modals.innerHTML=modal('assign-modal','Một người phù hợp để đồng hành.',`<p id="assign-summary"></p><form id="assign-form"><input name="visit_id" type="hidden"><div class="field"><label for="staff-select">Chuyên viên chăm sóc</label><select id="staff-select" name="caregiver_id" required></select></div><button class="btn" type="submit">Xác nhận phân công</button></form>`,'Điều phối chăm sóc')+modal('detail-modal','Thông tin ca chăm sóc.','<div id="visit-detail"></div>');
  }
  function render() { if(role==='family') renderFamily(); else if(role==='caregiver') renderCaregiver(); else renderCoordinator(); ui.icons(view); ui.icons(modals); main.hidden=false; access.hidden=true; }
  async function act(action) {
    if(state.busy) return; state.busy=true;
    try { await action(); } catch(error) { ui.notify(issue(error)); } finally { state.busy=false; }
  }
  document.addEventListener('click', async e => {
    const button=e.target.closest('[data-action]'); if(!button || !state.profile) return;
    const action=button.dataset.action, id=button.dataset.id;
    if(action==='book') { ui.open(state.relatives.length?'booking-modal':'relative-modal'); if(!state.relatives.length) ui.notify('Thêm người thân trước khi đặt ca nhé.'); }
    if(action==='refresh') await act(async()=>{ui.close(); await load(); ui.notify('Đã cập nhật lịch chăm sóc.');});
    if(action==='choose-visit') { state.selected=id; render(); }
    if(action==='filter') { state.filter=button.dataset.filter; render(); }
    if(action==='start') await act(async()=>{button.disabled=true; try { await query(auth.client.rpc('start_homa_visit',{p_visit_id:id})); await load(); ui.notify('Ca chăm sóc đã bắt đầu.'); } finally {button.disabled=false;} });
    if(action==='rate') await act(async()=>{await query(auth.client.rpc('rate_homa_visit',{p_visit_id:id,p_rating:Number(button.dataset.rating)})); await load(); ui.notify('Cảm ơn đánh giá của bạn.');});
    if(action==='assign') {
      const visit=state.visits.find(v=>v.id===id); if(!visit) return;
      document.querySelector('#assign-form input[name="visit_id"]').value=id;
      document.getElementById('assign-summary').textContent=`${relation(visit)?.full_name} · ${dateText(visit.care_date)} · 18:00–22:00`;
      const available=state.staff.filter(p=>!state.visits.some(v=>v.caregiver_id===p.id && v.care_date===visit.care_date));
      document.getElementById('staff-select').innerHTML=available.length?available.map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join(''):'<option value="">Chưa có chuyên viên trống lịch</option>';
      document.querySelector('#assign-form button').disabled=!available.length; ui.open('assign-modal');
    }
    if(action==='detail') {
      const visit=state.visits.find(v=>v.id===id); if(!visit) return;
      document.getElementById('visit-detail').innerHTML=`${pill(visit.status)}<h3 style="margin:18px 0 8px">${esc(relation(visit)?.full_name)}</h3><p>${dateText(visit.care_date)} · 18:00–22:00</p><p>Gia đình: ${esc(family(visit)?.full_name)}</p><p>Chuyên viên: ${esc(caregiver(visit)?.full_name || 'Chưa phân công')}</p><div class="report-note">${esc(visit.care_note || 'Chưa có lưu ý thêm')}</div>${visit.report_text?`<h3>Nhật ký chăm sóc</h3><div class="report-note">${esc(visit.report_text)}</div><p>${esc(visit.mood)}</p><p>${esc(visit.next_note)}</p>`:''}`; ui.open('detail-modal');
    }
  });
  document.addEventListener('change', e=>{if(!e.target.matches('.task input')) return; const inputs=[...document.querySelectorAll('.task input')],done=inputs.filter(x=>x.checked).length; document.getElementById('task-count').textContent=`${done}/4 hoạt động`; document.querySelector('.progress-bar span').style.width=`${done/4*100}%`;});
  document.addEventListener('submit', async e=>{
    const form=e.target; if(!['relative-form','booking-form','report-form','assign-form'].includes(form.id)) return;
    e.preventDefault(); if(state.busy) return;
    state.busy=true; const button=form.querySelector('button[type="submit"]'); const text=button.textContent; button.disabled=true; button.textContent='Đang lưu…';
    const message=form.closest('.modal')?.querySelector('[data-form-message]') || form.querySelector('[data-form-message]'); if(message){message.className='form-message';message.textContent='';}
    try {
      const fields=Object.fromEntries(new FormData(form));
      if(form.id==='relative-form') { if(fields.full_name.trim().length<2 || fields.area.trim().length<2) throw new Error('invalid_form'); await query(auth.client.from('relatives').insert({family_id:state.profile.id,full_name:fields.full_name.trim(),relationship:fields.relationship,age:Number(fields.age),area:fields.area.trim(),preferences:fields.preferences.trim()})); }
      if(form.id==='booking-form') await query(auth.client.rpc('book_homa_visit',{p_relative_id:fields.relative_id,p_care_date:fields.care_date,p_note:fields.care_note.trim()}));
      if(form.id==='assign-form') await query(auth.client.rpc('assign_homa_visit',{p_visit_id:fields.visit_id,p_caregiver_id:fields.caregiver_id}));
      if(form.id==='report-form') { const tasks=[...document.querySelectorAll('.task input')].map(x=>x.checked); if(tasks.length!==4 || tasks.some(x=>!x)) throw new Error('incomplete_tasks'); await query(auth.client.rpc('complete_homa_visit',{p_visit_id:form.dataset.visit,p_tasks:tasks,p_mood:fields.mood,p_report:fields.report_text.trim(),p_next_note:fields.next_note.trim()})); }
      ui.close(); await load(); ui.notify({'relative-form':'Đã lưu thông tin người thân.','booking-form':'Đã gửi yêu cầu chăm sóc. Điều phối viên sẽ tiếp nhận.','assign-form':'Đã phân công chuyên viên.','report-form':'Đã hoàn thành ca và gửi nhật ký đến gia đình.'}[form.id]);
    } catch(error) { const copy=error.message==='invalid_form'?'Bạn nhập đầy đủ tên và khu vực chăm sóc nhé.':issue(error); if(message){message.textContent=copy;message.className='form-message show'}else ui.notify(copy); }
    finally {state.busy=false;button.disabled=false;button.textContent=text;}
  });
  document.getElementById('sign-out').addEventListener('click', async()=>{try {await auth.logout();}catch(error){ui.notify(error.message);}});
  async function boot() {
    if(!auth?.configured) { blocked('Không gian chăm sóc đang được chuẩn bị.','Bạn có thể trở lại trang chủ và tìm hiểu các dịch vụ của HomaCare.'); return; }
    try {
      const current=await auth.profile();
      if(!current) {location.replace('auth.html?role='+role+(new URLSearchParams(location.search).get('booking')==='1'?'&booking=1':''));return;}
      if(current.role!==role) {auth.go(current.role);return;}
      state.profile=current; await load();
      if(role==='family' && new URLSearchParams(location.search).get('booking')==='1') ui.open(state.relatives.length?'booking-modal':'relative-modal');
      auth.client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){main.hidden=true;location.replace('auth.html?role='+role);}});
    } catch(error) {blocked('Chưa tải được không gian chăm sóc.','Hãy kiểm tra kết nối rồi tải lại trang.');}
  }
  boot();
})();
